### ISSUE TITLE
installation via composer

### ISSUE THREAD

**Issue by tomekjordan** [tpay-com/tpay-magento2-basic#1]
Your repo is not registered on official composer repos, so installation via require tpaycom/magento2basic is not working

manual installation is also not working because there are other module names than you specified
"php bin/magento module:enable tpaycom_tpay" simply cannot handle it - check your repo structure

**Comment by piotrjozwiak** [comment]
Thank you for reply, we have updated the readme file.
This module is registered at [packagist](https://packagist.org/packages/tpaycom/magento2basic) and works properly with composer require tpaycom/magento2basic  command.
