### ISSUE TITLE
Mage-OS support

### ISSUE THREAD

**Issue by adamwaclawczyk** [tpay-com/tpay-magento2-basic#36]
Currently this module's composer.json

https://github.com/tpay-com/tpay-magento2-basic/blob/82dc7a824eaf0f3d3a0d1ae38373b412e3586eb8/composer.json#L14

 specifies a require on Magento's product-community-edition meta package, according to [docs](https://developer.adobe.com/commerce/php/development/versioning/dependencies/):
> Do not specify a dependency on meta packages (e.g. product-community-edition).

Since mage-os uses a different meta-package this constraint cannot be satisfied.
PR https://github.com/tpay-com/tpay-magento2-basic/pull/35 should fix this.

**Comment by kwojc** [comment]
Fixed in 2.0.0
