### ISSUE TITLE
Nieaktualizowany stan zamówienia

### ISSUE THREAD

**Issue by mrk-dzie** [tpay-com/tpay-magento2-basic#4]
Po poprawnej płatności zamówienie zmienia swój status na "Processing", jednak stan ("state") pozostaje nie zmieniony (cały czas jest "pending_payment")

**Comment by piotrjozwiak** [comment]
Dziękujemy za zgłoszenie. Poprawka została wydana w commit 41edf9c403b2bb9b7fbbc203cfa5f27525eaa405
Prosimy zaktualizować moduł do wersji 1.4.4
