### ISSUE TITLE
Nie można zainstalować z najnowszą wersją magento 2.4

### ISSUE THREAD

**Issue by mrk-dzie** [tpay-com/tpay-magento2-basic#6]
Podczas próby instalacji z najnowszą wersją Magento 2.4, która wymaga PHP w wersji 7.3 lub 7.4 wyskakuje następujący błąd:
`- tpaycom/magento2basic 1.5.1 requires magento/product-community-edition ^2.3 -> satisfiable by magento/product-community-edition[2.4.0].
`

**Comment by mrk-dzie** [comment]
@piotrjozwiak Czy moduł będzie zaktualizowany, tak aby był kompatybilny z najnowszą wersją Magento?

**Comment by piotrjozwiak** [comment]
@mrk-dzie Tak, przewidujemy aktualizację w najbliższym czasie.

**Comment by Serwach** [comment]
@piotrjozwiak Również czekam na update wtyczki

**Comment by mrk-dzie** [comment]
@piotrjozwiak Czy jest znany przewidywany czas aktualizacji?

**Comment by piotrjozwiak** [comment]
Aktualizacja została wydana, można instalować moduł z wersjami Magento 2.3.* i 2.4.* oraz z każdą wersją PHP >=7
https://github.com/tpay-com/tpay-magento2-basic/releases/tag/1.5.2
